jose/basic_app/urls.py
from django.urls import path
from basic_app import views


app_name = "basic_app"   

urlpatterns = [
    path("", views.HomePage.as_view(), name='home'),
    path("artists/artist1/", views.ArtistOne.as_view(), name='artistone'),
    path("artists/artist2/", views.ArtistTwo.as_view(), name='artisttwo'),
    path("managers/manager1/", views.ManagerOne.as_view(), name='managerone'),
    path("managers/manager2/", views.ManagerTwo.as_view(), name='managertwo'),
    path("about/", views.About.as_view(), name='about'),
    path("Faq/", views.FAQ.as_view(), name='faq'),
    path("legal/", views.Legal.as_view(), name='legal'),
    path("contact/", views.contact_form, name='contact'),
    path("contact-success/", views.ContactSuccess.as_view(), name='contact-success'),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jose/jose/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('basic_app.urls', namespace='basic_app')),
]

jose/basic_app/models.py
from django.db import models

# Create your models here.
class ContactForm(models.Model):
    contact_name = models.CharField(max_length=100)
    contact_email = models.EmailField(max_length=100)
    contact_subject = models.CharField(max_length=100)
    contact_message = models.CharField(max_length=900)

jose/basic_app/forms.py
from django import forms
from .models import ContactForm

class ContactUsForm(forms.ModelForm):
    class Meta:
        model = ContactForm
        fields = ['contact_name', 'contact_email', 'contact_subject', 'contact_message']
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["contact_name"].widget.attrs.update({
            "type":"text", 
            "placeholder": "Name", 
            "maxlength":"40", 
            "minlength":"5",
        })

        self.fields["contact_email"].widget.attrs.update({
            "type":"email", 
            "placeholder":"Email",  
            "maxlength":"40", 
            "minlength":"5",
        })
        
        self.fields["contact_subject"].widget.attrs.update({
            "type":"text",
            "placeholder": "Subject",  
            "maxlength":"40", 
            "minlength":"5",
        })

        self.fields["contact_message"].widget.attrs.update({
            "type":"text",
            "placeholder": "Your Message",  
            "maxlength":"999", 
            "minlength":"5",
            "row": "4"
        })

jose/basic_app/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from .forms import ContactUsForm

# Create your views here.


def contact_form(request):
    if request.method == 'POST':
        form = ContactUsForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('basic_app:contact-success')
    else:
        form = ContactUsForm()
    return render(request, template_name='contact-us.html', context={'contact':form})


class HomePage(TemplateView):
    template_name = 'index.html'

class ArtistOne(TemplateView):
    template_name = 'artists/artists1.html'

class ArtistTwo(TemplateView):
    template_name = 'artists/artists2.html'

class About(TemplateView):
    template_name = 'about.html'

class ManagerOne(TemplateView):
    template_name = 'managers/manager1.html'

class ManagerTwo(TemplateView):
    template_name = 'managers/manager2.html'

class FAQ(TemplateView):
    template_name = 'faq.html'

class Legal(TemplateView):
    template_name = 'legal.html'

class ContactSuccess(TemplateView):
    template_name = 'contact-success.html'

jose/templates/about.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>¿Qué es DjMarfu.com?</title>
    <meta name="description" content="Contratación de artistas. Directorio de artistas. Contrata todo tipo de artistas. Contratación de artistas " />
    <meta name="keywords" content="contratacion artistas, contratacion cantantes, contratación artistas, contratación cantantes, grupos de musica, contratación de grupos de musica,espectáculo,espectáculo,espectaculos,espectaculo,música,musica,musica urbana,musica popular,estilos musicales,teatro,fiesta,payasos,magos " />
    <meta name="robots" content="index,follow" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon" />
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/final-packed.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,600|Roboto:400,400i,700,900" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/print-packed.css' %}" media="print" />
    <script>
        
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
        
        ga('create', 'UA-788438-1', 'auto');ga('send', 'pageview');
        </script>
    <script src="//www.unaplauso.com/js/ua2.5-final.packed.js" type="text/javascript"></script>
    <script async src="//www.unaplauso.com/js/ua2.5-lang_es.packed.js" type="text/javascript"></script>

    <style>
        .navbar-brand a {
            color: rgb(219, 9, 9);
            text-decoration: none;
        }
    </style>
</head>
<body>	<div id="header">
<div class="contenidor cabecera">
    <div class="navbar-brand">
        <a href="{% url 'basic_app:home' %}">Dj Marfu <br>!QUE NO PARE LA FIESTA! <i class="fa-solid fa-music"></i></a>
    </div>

<div id="anunciate"><a rel="nofollow" href="{% url 'basic_app:about' %}">¡Anúnciate gratis!</a></div>
<div id="barra">
<ul class="menu clearfix">
<li class="anuncios clearfix"><strong>19.116 anuncios</strong></li>
<li class="contacto"><a href="{% url 'basic_app:contact' %}" rel="nofollow">Contacto</a></li>
<li><a href="//quenoparelafiesta.es" target="_blank"><span>Blog</span></a></li>
</ul>
<div id="pestanas">
<ul>
<li><a href="{% url 'basic_app:artistone' %}"><span><span class="underline">Artistas</span></span></a></li>
<li><a href="{% url 'basic_app:managerone' %}"><span><span class="underline">Managers</span></span></a></li>
</ul>
</div>
<div class="cboth">
<b class="b1k"></b><b class="b2k"></b><b class="b3k"></b><b class="b4k"></b>
<div class="contentk"><div>

</div></div>
<b class="b4k"></b><b class="b3k"></b><b class="b2k"></b><b class="b1k"></b>
</div>
</div>
</div>
</div>
<hr class="dnone" />
<div class="contenidor queesunplauso">
<div id="breadcrumb">
</div>
<div class="p5_10">
<h1>Quiénes somos</h1><p><strong>DjMarfu.pitónencualquierlugar.com</strong> es un buscador de talentos para amenizar tus eventos y hacer que no pare la fiesta. Desde magos, cantantes y payasos, hasta salones, caterings, servicios de fotografía y managers.</p><p>La web presenta la mayor oferta de espectáculos en España, con más de 25.000 artistas, más de 100.000 clientes registrados y más de 500.000 eventos organizados hasta el momento.</p><p>Tras una década de haber crecido en Grupo Intercom, unAplauso se reinventa y a finales de 2018 es adquirida por Carlos Neira, Sergi López y Santi Alcaide, quienes trabajaron para la empresa y decidieron emprender con un proyecto profesional, que busca consolidar la plataforma como sitio de referencia en la contratación de artistas de pequeño formato en toda España, México y Alemania.</p>
</div>
</div>
<hr class="dnone" />
<div class="contenidor footer">

<div class="social">
<p>
<span>¡Síguenos!</span>
<a href="//www.facebook.com/pages/unAplauso/41439617363" target="_blank"><img alt="unAplauso Facebook" src="//www.unaplauso.com/img/ua2.5-facebook-24.png"></a>
<a href="https://twitter.com/#!/unAplauso_es" target="_blank"><img alt="unAplauso Twitter" src="//www.unaplauso.com/img/ua2.5-twitter-24.png"></a>
<a href="https://plus.google.com/112731728407308610415" target="_blank" rel="publisher"><img alt="unAplauso Google plus" src="//www.unaplauso.com/img/ua2.5-googleplus-24.png"></a>
</p>
</div>

</div>
<script type="text/javascript">
        </script>
<script type="text/javascript">
function temporizador(){ ga('send', {hitType: 'event', eventCategory: 'general', eventAction: 'temporizador', eventLabel: 'mas1Min'}); }
window.setTimeout(temporizador, 60000);
</script>
</body>
</html>

jose/templates/contact-success.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Contacto</title>
    <meta name="description" content="Contratación de artistas. Directorio de artistas. Contrata todo tipo de artistas. Contratación de artistas " />
    <meta name="keywords" content="contratacion artistas, contratacion cantantes, contratación artistas, contratación cantantes, grupos de musica, contratación de grupos de musica,espectáculo,espectáculo,espectaculos,espectaculo,música,musica,musica urbana,musica popular,estilos musicales,teatro,fiesta,payasos,magos " />
    <meta name="robots" content="index,follow" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon" />
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/final-packed.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,600|Roboto:400,400i,700,900" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/print-packed.css' %}" media="print" />
    <script>
        
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
        
        ga('create', 'UA-788438-1', 'auto');ga('send', 'pageview');
        </script>
    <script src="//www.unaplauso.com/js/ua2.5-final.packed.js" type="text/javascript"></script>
    <script async src="//www.unaplauso.com/js/ua2.5-lang_es.packed.js" type="text/javascript"></script>

    <style>
        .navbar-brand a {
            color: rgb(219, 9, 9);
            text-decoration: none;
        }
    </style>
</head>
<body>	<div id="header">
<div class="contenidor cabecera">
    <div class="navbar-brand">
        <a href="{% url 'basic_app:home' %}">Dj Marfu <br>!QUE NO PARE LA FIESTA! <i class="fa-solid fa-music"></i></a>
    </div>

<div id="anunciate"><a rel="nofollow" href="{% url 'basic_app:about' %}">¡Anúnciate gratis!</a></div>
<div id="barra">
<ul class="menu clearfix">
<li class="anuncios clearfix"><strong>19.116 anuncios</strong></li>
<li class="contacto"><a href="{% url 'basic_app:contact' %}" rel="nofollow">Contacto</a></li>
<li><a href="//quenoparelafiesta.es" target="_blank"><span>Blog</span></a></li>
</ul>
<div id="pestanas">
<ul>
<li><a href="{% url 'basic_app:artistone' %}"><span><span class="underline">Artistas</span></span></a></li>
<li><a href="{% url 'basic_app:managerone' %}"><span><span class="underline">Managers</span></span></a></li>
</ul>
</div>
<div class="cboth">
<b class="b1k"></b><b class="b2k"></b><b class="b3k"></b><b class="b4k"></b>
<div class="contentk"><div>

</div></div>
<b class="b4k"></b><b class="b3k"></b><b class="b2k"></b><b class="b1k"></b>
</div>
</div>
</div>
</div>
<hr class="dnone" />

<script type="text/javascript">
    var TestValidation = {
        someFormValidator: null,
        init: function() {
            this.someFormValidator = new Validation('formSugerencia', {
                onFormInvalid: function(failures) {
                    failures.each(function(fail) {
                        $('validation-errors-sugerencia').adopt(new Element('li').setHTML(fail));
                    });
                    $('form-errors-sugerencia').setStyles({display: 'block'});
                    var scroll = new Fx.Scroll('form-errors-sugerencia');
                    scroll.toElement('validation-errors-sugerencia');
                    var mySlide = new Fx.Slide('form-errors-sugerencia',{mode: 'horizontal'});
                    mySlide.hide();
                    mySlide.slideIn();
                },
                onFormValid: function() {
                    var mySlide2 = new Fx.Slide('form-errors-sugerencia');
                    mySlide2.slideOut();
                    mySlide2.hide();
                    $('formSugerencia').submit();
                    
                    // XGF # formulari Ajax no introsiu	
                    //new Fx.Slide('formContactarContent').hide(); //slideOut();	
                    //var out = $('formRecomendarOut').empty().addClass('ajax-loading');
                    //var sender = new Request();
                    //sender.onSuccess = function(responseText, responseXML){
                    //	out.removeClass('ajax-loading');
                    //	out.addClass('sended');
                    //	out.set('html', responseText); 
                    //	$('formRecomendar').reset();
                    //};
                    //sender.send({data: $('formRecomendar'), url: $('formRecomendar').get('action')});
    
                },		
                onElementValidating: function(el) {
                    el.removeClass('valid').removeClass('error');
                },
                onElementInvalid: function(el, err) {
                    el.addClass('error');
                },
                onElementValid: function(el) {
                    el.addClass('valid');
                }
            });	
            $('formSugerencia').addEvent('submit', function(e) {
                new Event(e).stop();
                $('validation-errors-sugerencia').empty();
                TestValidation.someFormValidator.validate();
            });
        }
    }
    
    window.addEvent("domready", TestValidation.init.bind(TestValidation));
    
    </script>
<div class="contenidor contactar">
    <div id="breadcrumb">
    </div>
    <div class="m0_auto w60">
    <h1>Contactar Exito</h1>
    
    </div></div>
    <b class="b4"></b><b class="b3"></b><b class="b2"></b><b class="b1"></b>
    </div>
    </div>
    </div>
    <hr class="dnone" />
<div class="contenidor footer">

<div class="social">
<p>
<span>¡Síguenos!</span>
<a href="//www.facebook.com/pages/unAplauso/41439617363" target="_blank"><img alt="unAplauso Facebook" src="//www.unaplauso.com/img/ua2.5-facebook-24.png"></a>
<a href="https://twitter.com/#!/unAplauso_es" target="_blank"><img alt="unAplauso Twitter" src="//www.unaplauso.com/img/ua2.5-twitter-24.png"></a>
<a href="https://plus.google.com/112731728407308610415" target="_blank" rel="publisher"><img alt="unAplauso Google plus" src="//www.unaplauso.com/img/ua2.5-googleplus-24.png"></a>
</p>
</div>

</div>
<script type="text/javascript">
        </script>
<script type="text/javascript">
function temporizador(){ ga('send', {hitType: 'event', eventCategory: 'general', eventAction: 'temporizador', eventLabel: 'mas1Min'}); }
window.setTimeout(temporizador, 60000);
</script>
</body>
</html>

jose/templates/contact-us.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Contacto</title>
    <meta name="description" content="Contratación de artistas. Directorio de artistas. Contrata todo tipo de artistas. Contratación de artistas " />
    <meta name="keywords" content="contratacion artistas, contratacion cantantes, contratación artistas, contratación cantantes, grupos de musica, contratación de grupos de musica,espectáculo,espectáculo,espectaculos,espectaculo,música,musica,musica urbana,musica popular,estilos musicales,teatro,fiesta,payasos,magos " />
    <meta name="robots" content="index,follow" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon" />
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/final-packed.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,600|Roboto:400,400i,700,900" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/print-packed.css' %}" media="print" />
    <script>
        
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
        
        ga('create', 'UA-788438-1', 'auto');ga('send', 'pageview');
        </script>
    <script src="//www.unaplauso.com/js/ua2.5-final.packed.js" type="text/javascript"></script>
    <script async src="//www.unaplauso.com/js/ua2.5-lang_es.packed.js" type="text/javascript"></script>

    <style>
        .navbar-brand a {
            color: rgb(219, 9, 9);
            text-decoration: none;
        }
    </style>
</head>
<body>	<div id="header">
<div class="contenidor cabecera">
    <div class="navbar-brand">
        <a href="{% url 'basic_app:home' %}">Dj Marfu <br>!QUE NO PARE LA FIESTA! <i class="fa-solid fa-music"></i></a>
    </div>

<div id="anunciate"><a rel="nofollow" href="{% url 'basic_app:about' %}">¡Anúnciate gratis!</a></div>
<div id="barra">
<ul class="menu clearfix">
<li class="anuncios clearfix"><strong>19.116 anuncios</strong></li>
<li class="contacto"><a href="{% url 'basic_app:contact' %}" rel="nofollow">Contacto</a></li>
<li><a href="//quenoparelafiesta.es" target="_blank"><span>Blog</span></a></li>
</ul>
<div id="pestanas">
<ul>
<li><a href="{% url 'basic_app:artistone' %}"><span><span class="underline">Artistas</span></span></a></li>
<li><a href="{% url 'basic_app:managerone' %}"><span><span class="underline">Managers</span></span></a></li>
</ul>
</div>
<div class="cboth">
<b class="b1k"></b><b class="b2k"></b><b class="b3k"></b><b class="b4k"></b>
<div class="contentk"><div>

</div></div>
<b class="b4k"></b><b class="b3k"></b><b class="b2k"></b><b class="b1k"></b>
</div>
</div>
</div>
</div>
<hr class="dnone" />

<script type="text/javascript">
    var TestValidation = {
        someFormValidator: null,
        init: function() {
            this.someFormValidator = new Validation('formSugerencia', {
                onFormInvalid: function(failures) {
                    failures.each(function(fail) {
                        $('validation-errors-sugerencia').adopt(new Element('li').setHTML(fail));
                    });
                    $('form-errors-sugerencia').setStyles({display: 'block'});
                    var scroll = new Fx.Scroll('form-errors-sugerencia');
                    scroll.toElement('validation-errors-sugerencia');
                    var mySlide = new Fx.Slide('form-errors-sugerencia',{mode: 'horizontal'});
                    mySlide.hide();
                    mySlide.slideIn();
                },
                onFormValid: function() {
                    var mySlide2 = new Fx.Slide('form-errors-sugerencia');
                    mySlide2.slideOut();
                    mySlide2.hide();
                    $('formSugerencia').submit();
                    
                    // XGF # formulari Ajax no introsiu	
                    //new Fx.Slide('formContactarContent').hide(); //slideOut();	
                    //var out = $('formRecomendarOut').empty().addClass('ajax-loading');
                    //var sender = new Request();
                    //sender.onSuccess = function(responseText, responseXML){
                    //	out.removeClass('ajax-loading');
                    //	out.addClass('sended');
                    //	out.set('html', responseText); 
                    //	$('formRecomendar').reset();
                    //};
                    //sender.send({data: $('formRecomendar'), url: $('formRecomendar').get('action')});
    
                },		
                onElementValidating: function(el) {
                    el.removeClass('valid').removeClass('error');
                },
                onElementInvalid: function(el, err) {
                    el.addClass('error');
                },
                onElementValid: function(el) {
                    el.addClass('valid');
                }
            });	
            $('formSugerencia').addEvent('submit', function(e) {
                new Event(e).stop();
                $('validation-errors-sugerencia').empty();
                TestValidation.someFormValidator.validate();
            });
        }
    }
    
    window.addEvent("domready", TestValidation.init.bind(TestValidation));
    
    </script>
<div class="contenidor contactar">
    <div id="breadcrumb">
    </div>
    <div class="m0_auto w60">
    <h1>Contactar con <span>DjMarfu.com</span></h1>
    <div id="form-errors-sugerencia">
    <b class="b1l"></b><b class="b2l"></b><b class="b3l"></b><b class="b4l"></b>
    <div class="contentl"><div class="p10">   
    <h3>Por favor, corrige los siguientes errores:</h3>
    <ul id="validation-errors-sugerencia">
    </ul>	
    </div></div>
    <b class="b4l"></b><b class="b3l"></b><b class="b2l"></b><b class="b1l"></b>
    </div>    
    <div class="tacenter">
    <b class="b1"></b><b class="b2"></b><b class="b3"></b><b class="b4"></b>
    <div class="contentb"><div class="p10 prelative clearfix">	
    <fieldset>
    <legend>Enviar</legend>
    <p>Utiliza el siguiente formulario para enviarnos tu comentario</p>
    <div class="site-form">
        <form method="POST">
            {% csrf_token %}                           
                
                    {{ contact.contact_name }}  <br> <br>
                
                
                    {{ contact.contact_email }}  <br> <br>
                
                
                    {{ contact.contact_subject }} <br> <br>
                
                
                    {{ contact.contact_message }} <br> <br>
                
                
                    <button type="submit" class="site-btn primary-btn">Send message</button>
                
        </form>
    </div>
    </fieldset>
    </div></div>
    <b class="b4"></b><b class="b3"></b><b class="b2"></b><b class="b1"></b>
    </div>
    </div>
    </div>
    <hr class="dnone" />
<div class="contenidor footer">

<div class="social">
<p>
<span>¡Síguenos!</span>
<a href="//www.facebook.com/pages/unAplauso/41439617363" target="_blank"><img alt="unAplauso Facebook" src="//www.unaplauso.com/img/ua2.5-facebook-24.png"></a>
<a href="https://twitter.com/#!/unAplauso_es" target="_blank"><img alt="unAplauso Twitter" src="//www.unaplauso.com/img/ua2.5-twitter-24.png"></a>
<a href="https://plus.google.com/112731728407308610415" target="_blank" rel="publisher"><img alt="unAplauso Google plus" src="//www.unaplauso.com/img/ua2.5-googleplus-24.png"></a>
</p>
</div>

</div>
<script type="text/javascript">
        </script>
<script type="text/javascript">
function temporizador(){ ga('send', {hitType: 'event', eventCategory: 'general', eventAction: 'temporizador', eventLabel: 'mas1Min'}); }
window.setTimeout(temporizador, 60000);
</script>
</body>
</html>